label_for_try:
  type: QLabel
  alignment: center
  fontFamily: times
  fontPoint: 20
  fontBold: True
  text: "n: next\nm: save\nq: exit"

label_for_retry:
  type: QLabel
  alignment: center
  fontFamily: times
  fontPoint: 20
  fontBold: True
  text: "n: next\nq: exit"